app = "slither-english"
primary_region = "dfw"

[build]
dockerfile = "Dockerfile"

[env]
PORT = "3000"

[http_service]
auto_start_machines = true
auto_stop_machines = false
force_https = true
internal_port = 3000
min_machines_running = 1
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "512mb"
